version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=bucket

  app:
    build:
      context: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_INFLUX_URL=http://influxdb:8086
      - SPRING_INFLUX_TOKEN=admin:password
      - SPRING_INFLUX_BUCKET=bucket
      - SPRING_INFLUX_ORG=org
    depends_on:
      - influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: