version: '3.8'
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=
      - DOCKER_INFLUXDB_INIT_PASSWORD=
      - DOCKER_INFLUXDB_INIT_ORG=
      - DOCKER_INFLUXDB_INIT_BUCKET=

  app:
    build:
      context: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_INFLUX_URL=http://influxdb:8086/
      - SPRING_INFLUX_TOKEN=
      - SPRING_INFLUX_BUCKET=
      - SPRING_INFLUX_ORG=
    depends_on:
      - influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: